apiVersion: apps/v1
kind: Deployment
metadata:
  name: ibm-management-ingress-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ibm-management-ingress-operator
  template:
    metadata:
      labels:
        name: ibm-management-ingress-operator
    spec:
      serviceAccountName: ibm-management-ingress-operator
      containers:
        - name: ibm-management-ingress-operator
          image: quay.io/opencloudio/ibm-management-ingress-operator:latest
          command:
          - ibm-management-ingress-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "ibm-management-ingress-operator"
