apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ibm-management-ingress-operator
  labels:
    app.kubernetes.io/name: ibm-management-ingress-operator
    app.kubernetes.io/instance: ibm-management-ingress-operator
    app.kubernetes.io/managed-by: ibm-management-ingress-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ibm-management-ingress-operator
subjects:
- kind: ServiceAccount
  name: ibm-management-ingress-operator
  namespace: REPLACE_NAMESPACE
